version: "3.9"

services:
  web:
    build: .
    container_name: flask_celery_web
    ports:
      - "8080:8080"
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
      - rabbitmq

  worker:
    build: .
    container_name: flask_celery_worker
    command: celery -A tasks worker --loglevel=info
    environment:
      RABBIT_HOST: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: flask_celery_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"